---

- name: Restore from backup | verify pre-restore
  hosts: localhost
  gather_facts: false
  tasks:
    - { name: "Get dependent roles via ansible-galaxy", local_action: "command ansible-galaxy role install -fr requirements.yml", tags: ["always"] }
    - { include_role: { name: "clusterverse/dynamic_inventory", apply: { tags: ["clusterverse_dynamic_inventory"]} }, tags: ["clusterverse_dynamic_inventory"] }
    - { name: "clusterverse | Copy ansible_ssh_private_key_file", local_action: "copy content={{cluster_vars[buildenv].ssh_connection_cfg.host.ansible_ssh_private_key_file}} dest='id_rsa_ansible_ssh_private_key_file' mode='0600'", when: "cluster_vars[buildenv].ssh_connection_cfg.host.ansible_ssh_private_key_file is defined", no_log: true, tags: ["always"] }
    - { name: "clusterverse | Copy bastion sshkey", local_action: "copy content={{cluster_vars[buildenv].ssh_connection_cfg.bastion.ssh_priv_key}} dest='id_rsa_bastion' mode='0600'", when: "cluster_vars[buildenv].ssh_connection_cfg.bastion.ssh_priv_key is defined", no_log: true, tags: ["always"] }

    - name: backup_restore | Verify the cluster's health *before* restore
      include_role: { name: "mongodb/verify" }


- name: Restore from backup | Perform the restore
  hosts: mongod
  tasks:
    - { include_role: { name: "clusterverse/_dependencies", apply: { tags: ["always"] } }, tags: ["always"], when: "'clusterverse_config' not in ansible_run_tags" }      # If we --skip-tags=clusterverse_config, this will ensure the variables from /cluster_defs are loaded.

    - name: backup_restore | Get replicaset status
      community.mongodb.mongodb_shell:
        login_user: "admin"
        login_password: "{{mongodb.admin_password}}"
        mongo_cmd: auto
        debug: true
        stringify: true
        eval: "rs.status()"
      delegate_to: "{{ groups['mongod'][0] }}"
      register: r__mongodb_shell__status

    - name: backup_restore | r__mongodb_shell__status
      debug: { msg: "{{r__mongodb_shell__status}}" }

    - name: backup_restore | run the restore on the primary
      block:
        - name: backup_restore | Ensure AWS CLI v2 is installed (for Ubuntu 16.04 and later)
          ansible.builtin.shell: |
            if ! command -v aws > /dev/null; then
              curl -s "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
              unzip /tmp/awscliv2.zip -d /tmp
              sudo /tmp/aws/install
            fi

        - name: backup_restore | Get the backup from S3  (NOTE - amazon.aws.s3_object module needs boto3 and botocore installed on the target host; it's not possible to get a valid version on old Ubuntu, so using aws cli)
          become: true
          ansible.builtin.shell: |
            AWS_ACCESS_KEY_ID={{ {{cluster_vars[buildenv].aws_access_key }} \
            AWS_SECRET_ACCESS_KEY={{ {{cluster_vars[buildenv].aws_secret_key }} \
            aws s3 cp s3://{{s3_backup_root}}/{{ ansible_date_time.date }}.gz {{remote_backup_path}} --region eu-west-1
            chown {{mongodb.sysuser}}:{{mongodb.sysgroup}} {{remote_backup_path}}
          args:
            creates: "{{remote_backup_path}}"

        - name: backup_restore | disable remote access via iptables
          block:
            - name: backup_restore / iptables | Add explicit ACCEPT rule for localhost and other mongodb cluster hosts
              become: true
              ansible.builtin.iptables:
                chain: INPUT
                protocol: tcp
                destination_port: "{{mongodb.mongod_conf.net.port}}"
                source: "{{item.ip}}"
                jump: ACCEPT
                comment: "backup_restore - Allow MongoDB cluster host ({{item.hostname}}) to connect"
              with_items: "{{ all_mongodb_hosts }}"

            - name: backup_restore / iptables | Add default REJECT rule
              become: true
              ansible.builtin.iptables:
                chain: INPUT
                protocol: tcp
                destination_port: "{{mongodb.mongod_conf.net.port}}"
                jump: REJECT
                comment: "backup_restore - Reject all external (non-cluster) connections"

        - name: backup_restore | drop the existing databases
          community.mongodb.mongodb_shell:
            login_user: "admin"
            login_password: "{{hostvars['localhost']['mongodb']['admin_password']}}"
            mongo_cmd: auto
            debug: true
            stringify: true
            db: "{{item}}"
            eval: "db.dropDatabase()"
          register: r__mongodb_drop_db
          with_items: ['pro_db', 'anonymizedDataConfidential_db']

        - name: backup_restore | restore the backup
          ansible.builtin.shell: |
            mongorestore --username admin --password {{hostvars['localhost']['mongodb']['admin_password']}} --authenticationDatabase admin --gzip --archive={{remote_backup_path}}
          register: r__mongorestore_start
          async: 7200
          poll: 0

        - name: backup_restore | poll async restore job (max 2h)
          async_status: { jid: "{{ r__mongorestore_start.ansible_job_id }}" }
          register: r__mongorestore_async
          until: r__mongorestore_async.finished
          retries: 120
          delay: 60

        - name: backup_restore | debug r__mongorestore_async
          debug: { msg: "{{r__mongorestore_async}}" }

        - name: backup_restore | reenable remote access via iptables
          block:
            - name: backup_restore / iptables | Remove the default REJECT rule
              become: true
              ansible.builtin.iptables:
                chain: INPUT
                protocol: tcp
                destination_port: "{{mongodb.mongod_conf.net.port}}"
                jump: REJECT
                state: absent
                comment: "backup_restore - Reject all external (non-cluster) connections"

            - name: backup_restore / iptables | Remove the explicit ACCEPT rule for localhost and other mongodb cluster hosts
              become: true
              ansible.builtin.iptables:
                chain: INPUT
                protocol: tcp
                destination_port: "{{mongodb.mongod_conf.net.port}}"
                source: "{{item.ip}}"
                jump: ACCEPT
                state: absent
                comment: "backup_restore - Allow MongoDB cluster host ({{item.hostname}}) to connect"
              with_items: "{{ all_mongodb_hosts }}"

        - name: backup_restore | remove backup file
          become: true
          ansible.builtin.file:
            path: "{{remote_backup_path}}"
            state: absent
      delegate_to: "{{ primary_host }}"
      run_once: true
      vars:
        remote_backup_path: "{{hostvars['localhost']['mongodb']['mongod_conf']['storage']['dbPath']}}/__backup_{{ ansible_date_time.date }}.gz"
        primary_host: "{{ ((r__mongodb_shell__status | default([]) | json_query(\"transformed_output.members[?stateStr==`PRIMARY`].name\"))[0]).split('.')[0] }}"
        all_mongodb_hosts: "{{hostvars | dict2items | json_query(\"[].{hostname: key, ip: value.ansible_host}\") + [{'hostname': 'localhost', 'ip': '127.0.0.1'}] }}"

    - name: backup_restore | update users
      include_role:
        name: mongodb/build
        tasks_from: mongodb-users.yml

- name: Restore from backup | verify post-restore
  hosts: localhost
  gather_facts: false
  tasks:
    - name: backup_restore | Verify the cluster's health *after* restore
      include_role: { name: "mongodb/verify" }
