#Note: Ansible <14 and the Azure libraries *require* Ubuntu <=24.04
ARG UBUNTU_VERSION=26.04

FROM ubuntu:${UBUNTU_VERSION}

#Note: Ansible <14 and the Azure libraries *require* Ubuntu <=24.04
ARG ANSIBLE_VERSION_SPEC=">=14.0.0"
ARG INSTALL_AZURE_COLLECTION=false

# Optionally override these at build time to match your host user:
# docker build --build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -g) ...
ARG USER_ID=9001
ARG GROUP_ID=9001
ARG USERNAME=dockerappuser

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/London
SHELL ["/bin/bash", "-c"]

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone \
    && apt-get update && apt-get install -y git iproute2 python3 python3-pip \
    && pip3 --no-cache-dir install --break-system-packages ansible${ANSIBLE_VERSION_SPEC} \
    && if [ ${INSTALL_AZURE_COLLECTION} = "true" ]; then \
         apt-get update && apt-get install -y python3-dev build-essential cmake libssl-dev pkg-config \
         && pip3 --no-cache-dir install --break-system-packages -r $(pip3 --no-cache-dir show ansible | grep ^Location | sed -r 's/^Location: (.*)/\1/')/ansible_collections/azure/azcollection/requirements*.txt; \
       fi \
    && apt-get install -y python3-boto3 python3-google-auth python3-jinja2 python3-jmespath python3-libvirt python3-lxml python3-netaddr python3-paramiko python3-pycdlib python3-setuptools python3-wheel python3-xmltodict \
    && apt-get purge -y build-essential cmake libssl-dev pkg-config \
    && apt-get -y --purge autoremove && apt-get -y autoclean && /bin/rm -rf /var/cache/apt/* /var/lib/apt/lists/*

WORKDIR /app

COPY . .

# Ensure the custom vault password client is executable by the runtime user
RUN chmod +x .vaultpass-client.py

RUN ansible-galaxy install -r requirements.yml

# Create non-root user matching host UID/GID.
RUN groupadd -g ${GROUP_ID} ${USERNAME} && useradd -m -u ${USER_ID} -g ${GROUP_ID} ${USERNAME} \
    && chown -R ${USERNAME}:${USERNAME} /app

USER ${USERNAME}
