---

roles:
  - name: mongodb
    src: https://github.com/clusterverse/mongodb
    version: master

collections:
  ## Mandatory
  - name: clusterverse.clusterverse
    version: ">=6.1.2,<6.2.0"
    source: https://galaxy.ansible.com

  - name: dseeley.tasks_serial
    version: ">=1.0.0,<1.1.0"
    source: https://galaxy.ansible.com

  - name: dseeley.ansible_vault_pipe
    version: ">=1.0.2,<1.1.0"
    source: https://galaxy.ansible.com

  ## Optional, if using libvirt
  - name: dseeley.inventory_lookup
    version: ">=1.0.1,<1.1.0"
    source: https://galaxy.ansible.com

  - name: dseeley.libvirt
    version: ">=2.3.1,<2.4.0"
    source: https://galaxy.ansible.com
